EventsGenerator: EventsGenerator.cc
	g++ $@.cc -I/home/mario/Software/pythia/pythia8309/include -lpythia8 -L/home/mario/Software/pythia/pythia8309/lib -I/home/mario/Software/HepMC3/hepmc3-install/include -lHepMC3 -L/home/mario/Software/HepMC3/hepmc3-install/lib -o $@
